<?php

namespace AppBundle\Repository;

/**
 * PrzystankiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrzystankiRepository extends \Doctrine\ORM\EntityRepository
{
}
